name: py36
channels:
  - anaconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - python=3.6.8
  - beautifulsoup4=4.6.0
  - gflags=2.2.2
  - h5py=2.9.0
  - hdf5=1.10.4
  - ipython=7.8.0
  - keras=2.2.4
  - feather-format=0.4.0
  - colorama=0.4.1
  - pytest=5.0.1
  - pylint=2.3.1
  - yapf=0.28.0
  - pandas=0.25.1
  - pyyaml=5.1.1
  - scikit-learn=0.21.2
  - scikit-image=0.15.0
  - seaborn=0.9.0
  - requests=2.22.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-datasets=1.2.0
  - tensorflow-hub=0.5.0
  - pysoundfile=0.10.2
  - re2=2019.08.01
  - structlog=19.1.0
  - prompt_toolkit=2.0.9
  - jupyter=1.0.0
  - graphviz=2.40.1
  - h5py=2.9.0
  - yaml=0.1.7
  - xgboost=0.90
  - pyhocon=0.3.51
  - scipy=1.3.1
  - seaborn=0.9.0
  - matplotlib=3.1.0
  - zeromq=4.3.1
  - torchvision=0.3.0
  - pytorch=1.1.0
  - lightgbm=2.2.1
  - numpy=1.16.4
  - pyzmq=18.1.0
  - pymongo=3.8.0
  - pymysql=0.9.3
  - glog=0.4.0
  - pyinstaller=3.4
  - ujson=1.35
  - pip:
    - gym==0.14.0
    - pyodps==0.8.3
    - tensorpack==0.9.8
    - redis==3.3.8
    - elasticsearch==7.0.4
    - mxnet==1.5.0
    - vnpy==1.9.2
